language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qtbase5-dev ninja-build libfuse-dev

script: cmake -GNinja . && ninja
