language: cpp

compiler:
  - gcc

os:
  - linux

before_install:
  # g++4.8.1
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake libqt4-dev libfuse-dev g++-4.8

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script:
  - $CXX --version
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CC_COMPILER=$CC . && make
